name: Create Image
on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set up JDK 1.17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: adopt
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Cache Maven packages
        uses: actions/cache@v4.0.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn package -DskipTests
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      - name: Obtain the repository name
        id: get_repo_name
        run:  echo "REPOSITORY_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_OUTPUT
      - name: Read the repository name
        run: echo "The repository name is ${{steps.get_repo_name.outputs.REPOSITORY_NAME}}"
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: src/main/docker/Dockerfile.jvm
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{steps.get_repo_name.outputs.REPOSITORY_NAME}}:${{ github.sha }}
